version: '3.8'
services:
  web:
    image: custom-nginx:latest  # <--- MUST match what Jenkins builds
    ports:
      - "8081:80"               # <--- Use 8081 to avoid the "Port 80" error
    networks:
      - site-net

networks:
  site-net:
    driver: overlay
