version: '3.8'

services:
  web-app:
    image: my-site-content:latest  # <--- FIXED THIS LINE
    networks:
      - site-net

  proxy:
    image: custom-nginx:latest
    ports:
      - "8081:80"
    networks:
      - site-net

networks:
  site-net:
    driver: overlay
