services:
  web-app:          # <--- This is the Service Name
    image: nginx:alpine
    networks:
      - site-net

  proxy:
    image: custom-nginx:latest
    ports:
      - "8081:80"
    networks:
      - site-net
